/* tslint:disable */
/* eslint-disable */
/**
 * Variable Density Yield Projection
 * API for the Variable Density Yield Projection service
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Message severity codes
 * @export
 * @enum {string}
 */
export enum EnumSeverity {
    Information = 'Information',
    Status = 'Status',
    Warning = 'Warning',
    Error = 'Error',
    FatalError = 'FatalError'
}

