/* tslint:disable */
/* eslint-disable */
/**
 * Variable Density Yield Projection
 * API for the Variable Density Yield Projection service
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface Filters
 */
export interface Filters {

    /**
     * only those polygons with the specified maintainer will be considered for inclusion in the output
     *
     * @type {string}
     * @memberof Filters
     */
    maintainer?: string;

    /**
     * only those polygons with the specified mapsheet will be considered for inclusion in the output
     *
     * @type {string}
     * @memberof Filters
     */
    mapsheet?: string;

    /**
     * only the polygon with the specified polygon number will be considered for inclusion in the output
     *
     * @type {string}
     * @memberof Filters
     */
    polygon?: string;

    /**
     * only the polygon with the specified polygon id will be considered for inclusion in the output
     *
     * @type {string}
     * @memberof Filters
     */
    polygonId?: string;
}
