/* tslint:disable */
/* eslint-disable */
/**
 * Variable Density Yield Projection
 * API for the Variable Density Yield Projection service
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * provides details about one parameter
 *
 * @export
 * @interface ParameterDetailsMessage
 */
export interface ParameterDetailsMessage {

    /**
     * the parameter name
     *
     * @type {string}
     * @memberof ParameterDetailsMessage
     */
    field?: string;

    /**
     * a brief description of the parameter's purpose
     *
     * @type {string}
     * @memberof ParameterDetailsMessage
     */
    shortDescription?: string;

    /**
     * if the parameter has a value, a description of the value
     *
     * @type {string}
     * @memberof ParameterDetailsMessage
     */
    parameterValue?: string;

    /**
     * a description of the parameter
     *
     * @type {string}
     * @memberof ParameterDetailsMessage
     */
    longDescription?: string;

    /**
     * the default value used if the parameter is not specified
     *
     * @type {string}
     * @memberof ParameterDetailsMessage
     */
    defaultValue?: string;
}
