/* tslint:disable */
/* eslint-disable */
/**
 * Variable Density Yield Projection
 * API for the Variable Density Yield Projection service
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import type { DebugOptions } from './debug-options'
import type { ExecutionOptions } from './execution-options'
import type { Filters } from './filters'
import type { ParametersUtils } from './parameters-utils'
/**
 * the parameters defining specifics of the run
 *
 * @export
 * @interface Parameters
 */
export interface Parameters {
  /**
   * Identifies the output file format. Default: YieldTable
   *
   * @type {string}
   * @memberof Parameters
   */
  outputFormat?: string

  /**
   * @type {ExecutionOptions}
   * @memberof Parameters
   */
  selectedExecutionOptions?: ExecutionOptions

  /**
   * @type {DebugOptions}
   * @memberof Parameters
   */
  selectedDebugOptions?: DebugOptions

  /**
   * The starting age value for the Age Range for generated yield tables.
   *
   * @type {number}
   * @memberof Parameters
   */
  ageStart?: number

  /**
   * The minimum value ageStart may have.
   *
   * @type {number}
   * @memberof Parameters
   */
  minAgeStart?: number

  /**
   * The maximum value ageStart may have.
   *
   * @type {number}
   * @memberof Parameters
   */
  maxAgeStart?: number

  /**
   * The ending age value for the Age Range for generated yield tables.
   *
   * @type {number}
   * @memberof Parameters
   */
  ageEnd?: number

  /**
   * The minimum value ageEnd may have.
   *
   * @type {number}
   * @memberof Parameters
   */
  minAgeEnd?: number

  /**
   * The maximum value ageEnd may have.
   *
   * @type {number}
   * @memberof Parameters
   */
  maxAgeEnd?: number

  /**
   * The starting year for the Year Range for generated yield tables.
   *
   * @type {number}
   * @memberof Parameters
   */
  yearStart?: number

  /**
   * The ending year for the Year Range for generated yield tables.
   *
   * @type {number}
   * @memberof Parameters
   */
  yearEnd?: number

  /**
   * Forces the inclusion of the specified calendar year in Yield tables.
   *
   * @type {number}
   * @memberof Parameters
   */
  forceYear?: number

  /**
   * The number of years to increment the current value for the Age and Year ranges.
   *
   * @type {number}
   * @memberof Parameters
   */
  ageIncrement?: number

  /**
   * The minimum value ageIncrement may have.
   *
   * @type {number}
   * @memberof Parameters
   */
  minAgeIncrement?: number

  /**
   * The maximum value ageIncrement may have.
   *
   * @type {number}
   * @memberof Parameters
   */
  maxAgeIncrement?: number

  /**
   * Determines how the Age Range and Year Range are to be combined when producing yield tables.
   *
   * @type {string}
   * @memberof Parameters
   */
  combineAgeYearRange?: string

  /**
   * Identifies how often or when progress will be reported from the application. In the case of a number being supplied, the number indicates the number of polygons to be processed between indications of progress.
   *
   * @type {string | number}
   * @memberof Parameters
   */
  progressFrequency?: string | number

  /**
   * Controls how much metadata is displayed in the Output and Error Logs.
   *
   * @type {string}
   * @memberof Parameters
   */
  metadataToOutput?: string

  /**
   * @type {Filters}
   * @memberof Parameters
   */
  filters?: Filters

  /**
   * @type {Array<ParametersUtils>}
   * @memberof Parameters
   */
  utils?: Array<ParametersUtils>
}
