/* tslint:disable */
/* eslint-disable */
/**
 * Variable Density Yield Projection
 * API for the Variable Density Yield Projection service
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import type { Parameters } from './parameters'
/**
 *
 *
 * @export
 * @interface ProjectionDcsvBody
 */
export interface ProjectionDcsvBody {
  /**
   * @type {Parameters}
   * @memberof ProjectionDcsvBody
   */
  projectionParameters?: Parameters

  /**
   * a file containing the input data in DCSV format.
   *
   * @type {Blob}
   * @memberof ProjectionDcsvBody
   */
  inputData?: Blob
}
