/* tslint:disable */
/* eslint-disable */
/**
 * Variable Density Yield Projection
 * API for the Variable Density Yield Projection service
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import type { Parameters } from './parameters'
/**
 *
 *
 * @export
 * @interface ProjectionHcsvBody
 */
export interface ProjectionHcsvBody {
  /**
   * @type {Parameters}
   * @memberof ProjectionHcsvBody
   */
  projectionParameters?: Parameters

  /**
   * a file containing the polygon input data in HCSV format.
   *
   * @type {Blob}
   * @memberof ProjectionHcsvBody
   */
  polygonInputData?: Blob

  /**
   * a file containing the layer input data in HCSV format.
   *
   * @type {Blob}
   * @memberof ProjectionHcsvBody
   */
  layerInputData?: Blob
}
