/* tslint:disable */
/* eslint-disable */
/**
 * Variable Density Yield Projection
 * API for the Variable Density Yield Projection service
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import type { Parameters } from './parameters'
/**
 *
 *
 * @export
 * @interface ProjectionScsvBody
 */
export interface ProjectionScsvBody {
  /**
   * @type {Parameters}
   * @memberof ProjectionScsvBody
   */
  projectionParameters?: Parameters

  /**
   * a file containing the polygon input data in HCSV format.
   *
   * @type {Blob}
   * @memberof ProjectionScsvBody
   */
  polygonInputData?: Blob

  /**
   * a file containing the layer input data in HCSV format.
   *
   * @type {Blob}
   * @memberof ProjectionScsvBody
   */
  layerInputData?: Blob

  /**
   * a file containing the history input data in HCSV format.
   *
   * @type {Blob}
   * @memberof ProjectionScsvBody
   */
  historyInputData?: Blob

  /**
   * a file containing the non-vegetation input data in HCSV format.
   *
   * @type {Blob}
   * @memberof ProjectionScsvBody
   */
  nonVegetationInputData?: Blob

  /**
   * a file containing the non-tree vegetation input data in HCSV format.
   *
   * @type {Blob}
   * @memberof ProjectionScsvBody
   */
  otherVegetationInputData?: Blob

  /**
   * a file containing the polygon id input data in HCSV format.
   *
   * @type {Blob}
   * @memberof ProjectionScsvBody
   */
  polygonIdInputData?: Blob

  /**
   * a file containing the species input data in HCSV format.
   *
   * @type {Blob}
   * @memberof ProjectionScsvBody
   */
  speciesInputData?: Blob

  /**
   * a file containing the VRI adjust input data in HCSV format.
   *
   * @type {Blob}
   * @memberof ProjectionScsvBody
   */
  vriAdjustInputData?: Blob
}
