/* tslint:disable */
/* eslint-disable */
/**
 * Variable Density Yield Projection
 * API for the Variable Density Yield Projection service
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ProjectionResponse
 */
export interface ProjectionResponse {

    /**
     * @type {Blob}
     * @memberof ProjectionResponse
     */
    yieldTable?: Blob;

    /**
     * @type {Blob}
     * @memberof ProjectionResponse
     */
    messages?: Blob;

    /**
     * @type {Blob}
     * @memberof ProjectionResponse
     */
    logMessages?: Blob;

    /**
     * @type {Blob}
     * @memberof ProjectionResponse
     */
    debugMessages?: Blob;
}
