export const speciesMap = {
  AC: 'Poplar',
  AT: 'Aspen',
  B: 'True Fir',
  BA: 'Amabilis Fir',
  BG: 'Grand Fir',
  BL: 'Alpine Fir',
  CW: 'Western Red Cedar',
  DR: 'Red Alder',
  E: 'Birch',
  EA: 'Alaska Paper Birch',
  EP: 'Common Paper Birch',
  FD: 'Douglas Fir',
  H: 'Hemlock',
  HM: 'Mountain Hemlock',
  HW: 'Western Hemlock',
  L: 'Larch',
  LA: 'Alpine Larch',
  LT: 'Tamarack',
  LW: 'Western Larch',
  MB: 'Bigleaf Maple',
  PA: 'Whitebark Pine',
  PF: 'Limber Pine',
  PJ: 'Jack Pine',
  PL: 'Lodgepole Pine',
  PW: 'Western White Pine',
  PY: 'Ponderosa (Yellow) Pine',
  S: 'Spruce',
  SB: 'Black Spruce',
  SE: 'Engelmann Spruce',
  SS: 'Sitka Spruce',
  SW: 'White Spruce',
  YC: 'Yellow Cedar',
}

// default Site Index Curve name for a species code
export const siteIndexCurveMap = {
  AC: 'Huang, Titus, and Lakusta (1994ac)',
  AT: 'Nigh, Krestov, and Klinka 2002',
  B: 'Chen and Klinka (2000ac)',
  BA: 'Nigh (2009)',
  BG: 'Nigh (2009)',
  BL: 'Chen and Klinka (2000ac)',
  CW: 'Nigh (2000)',
  DR: 'Nigh and Courtin (1998)',
  E: 'Nigh (2009)',
  EA: 'Nigh (2009)',
  EP: 'Nigh (2009)',
  FD: 'Thrower and Goudie (1992ac)',
  H: 'Nigh (1998)',
  HM: 'Means, Campbell, Johnson (1988ac)',
  HW: 'Nigh (1998)',
  L: 'Brisco, Klinka, Nigh 2002',
  LA: 'Brisco, Klinka, Nigh 2002',
  LT: 'Brisco, Klinka, Nigh 2002',
  LW: 'Brisco, Klinka, Nigh 2002',
  MB: 'Nigh and Courtin (1998)',
  PA: 'Thrower (1994)',
  PF: 'Thrower (1994)',
  PJ: 'Huang (1997ac)',
  PL: 'Thrower (1994)',
  PW: 'Curtis, Diaz, and Clendenen (1990ac)',
  PY: 'Nigh (2002)',
  S: 'Goudie (1984ac) (natural)',
  SB: 'Nigh, Krestov, and Klinka 2002',
  SE: 'Nigh (2015)',
  SS: 'Nigh (1997)',
  SW: 'Goudie (1984ac) (natural)',
  YC: 'Nigh (2000)',
}
