package ca.bc.gov.nrs.vdyp.common_calculators;

public interface SiteIndexConstants {
	
	/* establishment types */
	int SI_ESTAB_NAT = 0;
	int SI_ESTAB_PLA = 1;

	/* site index estimation (from height and age) types */
	int SI_EST_ITERATE = 0;
	int SI_EST_DIRECT = 1;
	
	/* age types */
	int SI_AT_TOTAL = 0;
	int SI_AT_BREAST = 1;

	/* forest regions */
	short FIZ_UNKNOWN = 0;
	short FIZ_COAST = 1;
	short FIZ_INTERIOR = 2;

	/* species indices */
	int SI_SPEC_A = 0;
	int SI_SPEC_ABAL = 1;
	int SI_SPEC_ABCO = 2;
	int SI_SPEC_AC = 3;
	int SI_SPEC_ACB = 4;
	int SI_SPEC_ACT = 5;
	int SI_SPEC_AD = 6;
	int SI_SPEC_AH = 7;
	int SI_SPEC_AT = 8;
	int SI_SPEC_AX = 9;
	int SI_SPEC_B = 10;
	int SI_SPEC_BA = 11;
	int SI_SPEC_BB = 12;
	int SI_SPEC_BC = 13;
	int SI_SPEC_BG = 14;
	int SI_SPEC_BI = 15;
	int SI_SPEC_BL = 16;
	int SI_SPEC_BM = 17;
	int SI_SPEC_BP = 18;
	int SI_SPEC_C = 19;
	int SI_SPEC_CI = 20;
	int SI_SPEC_CP = 21;
	int SI_SPEC_CW = 22;
	int SI_SPEC_CWC = 23;
	int SI_SPEC_CWI = 24;
	int SI_SPEC_CY = 25;
	int SI_SPEC_D = 26;
	int SI_SPEC_DG = 27;
	int SI_SPEC_DM = 28;
	int SI_SPEC_DR = 29;
	int SI_SPEC_E = 30;
	int SI_SPEC_EA = 31;
	int SI_SPEC_EB = 32;
	int SI_SPEC_EE = 33;
	int SI_SPEC_EP = 34;
	int SI_SPEC_ES = 35;
	int SI_SPEC_EW = 36;
	int SI_SPEC_EXP = 37;
	int SI_SPEC_FD = 38;
	int SI_SPEC_FDC = 39;
	int SI_SPEC_FDI = 40;
	int SI_SPEC_G = 41;
	int SI_SPEC_GP = 42;
	int SI_SPEC_GR = 43;
	int SI_SPEC_H = 44;
	int SI_SPEC_HM = 45;
	int SI_SPEC_HW = 46;
	int SI_SPEC_HWC = 47;
	int SI_SPEC_HWI = 48;
	int SI_SPEC_HXM = 49;
	int SI_SPEC_IG = 50;
	int SI_SPEC_IS = 51;
	int SI_SPEC_J = 52;
	int SI_SPEC_JR = 53;
	int SI_SPEC_K = 54;
	int SI_SPEC_KC = 55;
	int SI_SPEC_L = 56;
	int SI_SPEC_LA = 57;
	int SI_SPEC_LE = 58;
	int SI_SPEC_LT = 59;
	int SI_SPEC_LW = 60;
	int SI_SPEC_M = 61;
	int SI_SPEC_MB = 62;
	int SI_SPEC_ME = 63;
	int SI_SPEC_MN = 64;
	int SI_SPEC_MR = 65;
	int SI_SPEC_MS = 66;
	int SI_SPEC_MV = 67;
	int SI_SPEC_OA = 68;
	int SI_SPEC_OB = 69;
	int SI_SPEC_OC = 70;
	int SI_SPEC_OD = 71;
	int SI_SPEC_OE = 72;
	int SI_SPEC_OF = 73;
	int SI_SPEC_OG = 74;
	int SI_SPEC_P = 75;
	int SI_SPEC_PA = 76;
	int SI_SPEC_PF = 77;
	int SI_SPEC_PJ = 78;
	int SI_SPEC_PL = 79;
	int SI_SPEC_PLC = 80;
	int SI_SPEC_PLI = 81;
	int SI_SPEC_PM = 82;
	int SI_SPEC_PR = 83;
	int SI_SPEC_PS = 84;
	int SI_SPEC_PW = 85;
	int SI_SPEC_PXJ = 86;
	int SI_SPEC_PY = 87;
	int SI_SPEC_Q = 88;
	int SI_SPEC_QE = 89;
	int SI_SPEC_QG = 90;
	int SI_SPEC_R = 91;
	int SI_SPEC_RA = 92;
	int SI_SPEC_S = 93;
	int SI_SPEC_SA = 94;
	int SI_SPEC_SB = 95;
	int SI_SPEC_SE = 96;
	int SI_SPEC_SI = 97;
	int SI_SPEC_SN = 98;
	int SI_SPEC_SS = 99;
	int SI_SPEC_SW = 100;
	int SI_SPEC_SX = 101;
	int SI_SPEC_SXB = 102;
	int SI_SPEC_SXE = 103;
	int SI_SPEC_SXL = 104;
	int SI_SPEC_SXS = 105;
	int SI_SPEC_SXW = 106;
	int SI_SPEC_SXX = 107;
	int SI_SPEC_T = 108;
	int SI_SPEC_TW = 109;
	int SI_SPEC_U = 110;
	int SI_SPEC_UA = 111;
	int SI_SPEC_UP = 112;
	int SI_SPEC_V = 113;
	int SI_SPEC_VB = 114;
	int SI_SPEC_VP = 115;
	int SI_SPEC_VS = 116;
	int SI_SPEC_VV = 117;
	int SI_SPEC_W = 118;
	int SI_SPEC_WA = 119;
	int SI_SPEC_WB = 120;
	int SI_SPEC_WD = 121;
	int SI_SPEC_WI = 122;
	int SI_SPEC_WP = 123;
	int SI_SPEC_WS = 124;
	int SI_SPEC_WT = 125;
	int SI_SPEC_X = 126;
	int SI_SPEC_XC = 127;
	int SI_SPEC_XH = 128;
	int SI_SPEC_Y = 129;
	int SI_SPEC_YC = 130;
	int SI_SPEC_YP = 131;
	int SI_SPEC_Z = 132;
	int SI_SPEC_ZC = 133;
	int SI_SPEC_ZH = 134;
	
	/* equation indices */

}
